# Generated by Django 5.1.3 on 2024-11-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='tags',
            field=models.ManyToManyField(blank=True, to='apis.tag'),
        ),
    ]
