# Generated by Django 5.1.3 on 2024-11-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_tag_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='pub_date',
            new_name='published_date',
        ),
    ]
