# Generated by Django 5.1.3 on 2024-11-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_rename_polls_question_poll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id', '-date_created', 'title'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['id', '-date_created', 'title']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id', '-date_created', 'title']},
        ),
    ]
