# Generated by Django 5.1.3 on 2024-11-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_alter_poll_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='categories',
            field=models.ManyToManyField(blank=True, to='apis.category'),
        ),
    ]
